name: Build and Deploy

on:
  push:
    branches: ["main"]

env:
  IMAGE_NAME: ghcr.io/harshitagrawal22/docker_ci_cd_learning

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: HarshitAgrawal22
          password: ${{ secrets.GHCR_PAT }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: harshitagrawal22/docker_ci_cd_learning:latest
